### ISSUE TITLE
could you set the axios headers custom;

### ISSUE THREAD

**Issue by tingshuai** [tiagosiebler/bitget-api#15]
I want to reset http headers; but I fount it can not;  could you set it custom?

![1689508383596](https://github.com/tiagosiebler/bitget-api/assets/23158246/53eab276-9e0a-4ac5-867f-142761422c27)

**Comment by tiagosiebler** [comment]
Could you explain more on your use case for customising the request headers?

**Comment by tiagosiebler** [comment]
Closing this for now but feel free to reopen if you'd still like to discuss
