### ISSUE TITLE
Need add a type in FuturesPlanType

### ISSUE THREAD

**Issue by footcoderr** [tiagosiebler/bitget-api#16]
I found out while using the API below.
` cancelAllPlanOrders(productType: FuturesProductType, planType: FuturesPlanType): Promise<APIResponse<any>>;`

need to add **'normal_plan'** to the FuturesPlanType type.

**Comment by tiagosiebler** [comment]
Hi @footcoderr - sorry about the delay. I've updated it to add all the missing futures plan types, via #19 - will be available shortly in v1.1.2. If you notice anything else that's missing, please let me know. PRs are also welcome - especially for adding more response types for the api calls still returning `any`. Thanks!
