### ISSUE TITLE
getRecentTrades has required type symbol but Bitget's API says its not required

### ISSUE THREAD

**Issue by TYRANTHOSAURUS** [tiagosiebler/bitget-api#18]
Hi, 

I'm tryng to get all account history trades which seems impossible to do?

Bitget's API docs says i can get the trades without having to select a symbol, but the type inside the lib forces it.

Whats the best way to get ALL trade history regardless of symbol and possibly date?

Thanks

**Comment by tiagosiebler** [comment]
Can you let me know where you see that this would work without a symbol? I've checked both the spot and futures docs, and both say that "symbol" is required:
https://bitgetlimited.github.io/apidoc/en/spot/#get-recent-trades
https://bitgetlimited.github.io/apidoc/en/mix/#get-recent-fills

**Comment by TYRANTHOSAURUS** [comment]
After getting curious seeing "v1" in the url, there might be a version difference in our documents.

But what is the replacing one in v2 for this call? because this is the most important call for any trade documentation.

Recent fills and recent trades do not show pnl, history positions has it.

**Comment by tiagosiebler** [comment]
Ah, looks like that endpoint hasn't been added to the futures client yet. There's no method currently using the `history-position` endpoint:
https://github.com/tiagosiebler/bitget-api/blob/master/src/futures-client.ts#L317

Can I interest you in making a pull request to add it? Otherwise I'll try to get it added soon

**Comment by TYRANTHOSAURUS** [comment]
This is my first time I ever done something on Github or make a PR as a newbie dev so I hope I did everything alright.

[https://github.com/tiagosiebler/bitget-api/pull/20](url)

**Comment by tiagosiebler** [comment]
You did great, nicely done! Added a tiny comment just because some params are optional it'll be easier to use if the fn param is just one object instead of having all properties as individual parameters. Thanks also for including the version bump, it'll make the release process easier!
