### ISSUE TITLE
Add V2 copy trading endpoints

### ISSUE THREAD

**Issue by bongkook** [tiagosiebler/bitget-api#28]
hello.
Thank you for developing great open source.
There is no Copy Trading endpoint in the V2 API.
Is it possible to add it?

**Comment by tiagosiebler** [comment]
Hi @bongkook 

Not implemented yet:
https://github.com/tiagosiebler/bitget-api/blob/master/src/rest-client-v2.ts#L869

Definitely possible to add it, just need to work on it.

**Comment by bongkook** [comment]
thank you for the reply.
I'll be waiting.

**Comment by tiagosiebler** [comment]
Let's keep this open as a reminder, so it doesn't get lost. Thx

**Comment by HugForLuck** [comment]
Is there an estimation when this endpoint will be added?

**Comment by bongkook** [comment]
I hope it gets added as soon as possible.
thank you.

**Comment by JJ-Cro** [comment]
Hey, for all wondering, I have submitted a PR with updates, it should include all V2 endpoints now. Waiting for review and should be up quick!
