### ISSUE TITLE
Error INVALID_ACCESS_KEY

### ISSUE THREAD

**Issue by fromcouch** [tiagosiebler/bitget-api#33]
Hi, just trying to use this library but i don't understand what this error means:

```
{
  code: 400,
  message: 'Bad Request',
  body: {
    code: '40006',
    msg: 'Invalid ACCESS_KEY',
    requestTime: 1707473926922,
    data: null
  },
}
```

I was reviewed all the keys and are equal from bitget. 

My peace of code:

```
const { RestClientV2 } = require('bitget-api');

const client = new RestClientV2(process.env.APIKEY, process.env.SECRET, process.env.PASSPHRASE);
console.log(await client.getSpotAccount());
```

Thanks

**Comment by tiagosiebler** [comment]
Something is wrong with your key. Specifically, the way you're passing your credentials to the REST client is incorrect. The REST client accepts an object with your configuration (including api credentials) in the config. Here's an example:
https://github.com/tiagosiebler/bitget-api/blob/master/examples/rest-private-spot.ts#L11-L18

**Comment by tiagosiebler** [comment]
Btw I really recommend getting into typescript. These kind of mistakes would show in a really obvious way, without having to get lost trying to understand what went wrong.

**Comment by fromcouch** [comment]
omg, so sorry i will leave this until monday. My headache don't le me focus on that things today. Thanks for pointing me in the right direction, i was totally forgot to send the object in RestClientV2 and sent plain text.

I have a love/hate rellaitonship with TS. I try to use sometimes, with react and vue, but in nodejs i don't like it.

Thanks
