### ISSUE TITLE
Transaction fees

### ISSUE THREAD

**Issue by DoganM95** [tiagosiebler/bitget-api#42]
Just used your npm package to do my first api-call to buy a trading pair, that the bitget app says has "0 fees". Bought this pair before manually, indeed 0 fees. The first api call i did however, while using your npm package took fees from me. 

I haven't done direct http calls yet, so i cannot tell if this issue is caused by your package or not. But i hope however, that you have more info on this.

Thanks in advance.

**Comment by DoganM95** [comment]
It was USDC/USDT (spot), thanks for the fast response!

**Comment by tiagosiebler** [comment]
Hey @DoganM95 - the feedback I've gotten from Bitget is that the 0 fee promotions don't apply to API trades. Quite surprised as well about this, best I can recommend here is to get in touch with customer support via email or live chat on their website and request that API trades support this in future. Will close this issue in the meantime as it's not an issue with the SDK itself - just how the promotion on bitget's end works.

**Comment by DoganM95** [comment]
Hey Tiago, thanks alot for the information!
Seems like no one has noticed this before, even the bitget telegram channel had no idea...
Keep up the great work with the api btw, made my life a whole lot easier, appreciate that :)
